server:
  port: 8091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jpabook
    username: jin0kim326
    password: 1004
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: -> ?? system.out?? ??
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug #logger? ?? ????
#    org.hibernate.type: trace

