server:
  port: 8091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/querydsl
    username: jin0kim326
    password: 10041004
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#        use_sql_comments: true // jpql을 보는방법

#logging:
#  level:
#    org.hibernate.SQL: debug

